module.exports = Object.freeze({

  mongodburl:'localhost:27017/arduinocommdb',

// for use on server side
  ESP_CONFIG_STATE: ["ESP_UNCONFIGURED","ESP_CONFIGURED","ESP_OTA"],
  
  ESP_UNCONFIGURED:0,
  ESP_CONFIGURED:1,
  ESP_OTA:2,

// Used by ESP
  ESP_STATE: [
    "STATE_READY",                "STATE_WIFI_CONNECT",           "STATE_WIFI_ACTIVE",
    "STATE_ACCESS_POINT_CONNECT", "STATE_ACCESS_POINT_ACTIVE",    "STATE_SLEEP",
    "STATE_BOOTED",               "STATE_REQUEST_CONFIG",         "STATE_RESPONSE_CONFIG_DETAILS",
    "STATE_ACTIVE",               "STATE_PASSIVE",                "STATE_OTA_AVAILABLE",        
    "STATE_INIT_OTA",             "STATE_RECORD_DATA"
  ],

  STATE_READY: 0,
  STATE_WIFI_CONNECT: 1,
  STATE_WIFI_ACTIVE: 2,
  STATE_ACCESS_POINT_CONNECT: 3,
  STATE_ACCESS_POINT_ACTIVE: 4,
  STATE_SLEEP: 5,
  STATE_BOOTED: 6,
  STATE_REQUEST_CONFIG: 7,
  STATE_RESPONSE_CONFIG_DETAILS: 8,
  STATE_ACTIVE: 9,
  STATE_PASSIVE: 10,
  STATE_OTA_AVAILABLE: 11,
  STATE_INIT_OTA: 12,
  STATE_RECORD_DATA :13,
  STATE_DATA_ACK:101,

  CHANNEL: ["CONTROL", "CONFIGURATION", "DATA"],

  CONTROL: "control",
  CONFIGURATION: "configuration",
  DATA: "data"

});